# $FreeBSD: head/usr.sbin/bsdconfig/usermgmt/include/Makefile 291347 2015-11-26 01:14:27Z bdrewery $

FILESDIR=	${LIBEXECDIR}/bsdconfig/070.usermgmt/include
FILES=		messages.subr usermgmt.hlp

.include <bsd.prog.mk>
