# $FreeBSD: head/usr.sbin/bsdconfig/password/Makefile 291347 2015-11-26 01:14:27Z bdrewery $

SUBDIR= include share

FILESDIR=	${LIBEXECDIR}/bsdconfig/040.password
FILES=		INDEX USAGE

SCRIPTSDIR=	${FILESDIR}
SCRIPTS=	password

.include <bsd.prog.mk>
