# $FreeBSD: head/usr.sbin/bsdconfig/examples/Makefile 291347 2015-11-26 01:14:27Z bdrewery $

FILESDIR=	${SHAREDIR}/examples/bsdconfig
FILES=		add_some_packages.sh browse_packages_http.sh bsdconfigrc

.include <bsd.prog.mk>
