# $FreeBSD: head/usr.sbin/bsdconfig/usermgmt/Makefile 291347 2015-11-26 01:14:27Z bdrewery $

SUBDIR= include share

FILESDIR=	${LIBEXECDIR}/bsdconfig/070.usermgmt
FILES=		INDEX USAGE

SCRIPTSDIR=	${FILESDIR}
SCRIPTS=	groupadd groupdel groupedit useradd userdel useredit usermgmt

.include <bsd.prog.mk>
