# $FreeBSD: head/usr.sbin/bsdconfig/share/media/Makefile 301973 2016-06-16 21:14:25Z dteske $

FILESDIR=	${SHAREDIR}/bsdconfig/media
FILES=		any.subr cdrom.subr common.subr directory.subr dos.subr \
		floppy.subr ftp.subr http.subr httpproxy.subr network.subr \
		nfs.subr options.subr tcpip.subr ufs.subr usb.subr wlan.subr

.include <bsd.prog.mk>
