# $FreeBSD: head/usr.sbin/bsdconfig/console/include/Makefile 291347 2015-11-26 01:14:27Z bdrewery $

FILESDIR=	${LIBEXECDIR}/bsdconfig/080.console/include
FILES=		messages.subr

.include <bsd.prog.mk>
