#!/bin/sh
# -*- tab-width: 4 -*- ;; Emacs
# vi: set noexpandtab  :: Vi/ViM
############################################################ IDENT(1)
#
# $Title: Script for importing current working directory to git $
# $Copyright: 1999-2017 Devin Teske. All rights reserved. $
# $FrauBSD: pkgcenter/Mk/git_import 2018-07-04 04:06:08 +0000 freebsdfrau $
#
############################################################ INFORMATION
#
# Usage: git_import
#
############################################################ GLOBALS

#
# Global exit status
#
SUCCESS=0
FAILURE=1

#
# Utility pathnames
#
: ${GIT:=git}

############################################################ FUNCTIONS

eval2()
{
	echo "$*"
	eval "$@"
}

############################################################ MAIN

set -e

#
# Clean before import to prevent importing +MANIFEST et al.
#
make clean

#
# Import src directory without verification
#
if [ -d "$SRCDIR" ]; then
	echo $GIT add -v "$SRCDIR"
	added=$( $GIT add -v "$SRCDIR" )
	[ ! "$added" ] || eval2 $GIT commit --no-verify
fi

#
# Clean everything else to prevent importing compiled package
#
make distclean

#
# Import everything else
#
echo $GIT add -v .
added=$( $GIT add -v . )
[ ! "$added" ] || eval2 $GIT commit

################################################################################
# END
################################################################################
