# $FreeBSD: head/usr.sbin/bsdconfig/startup/share/Makefile 291347 2015-11-26 01:14:27Z bdrewery $

FILESDIR=	${SHAREDIR}/bsdconfig/startup
FILES=		rcconf.subr rcedit.subr rcvar.subr

.include <bsd.prog.mk>
