# $FrauBSD: pkgcenter/depend/libcmb/python/Makefile 2018-12-18 03:28:13 -0800 freebsdfrau $

all:

# Ready the directory for distribution
distclean:
	rm -f cmb/*.pyc *.pyc

# In our case, clean is distclean (*.pyc files are not important)
clean: distclean
