# $FreeBSD: head/usr.sbin/bsdconfig/security/include/Makefile 291347 2015-11-26 01:14:27Z bdrewery $

FILESDIR=	${LIBEXECDIR}/bsdconfig/130.security/include
FILES=		messages.subr securelevel.hlp

.include <bsd.prog.mk>
