#!/bin/sh
# -*- tab-width: 4 -*- ;; Emacs
# vi: set noexpandtab  :: Vi/ViM
############################################################ IDENT(1)
#
# $Title: Script for getting the package tag name from an RPM SPEC-file $
# $Copyright: 1999-2017 Devin Teske. All rights reserved. $
# $FrauBSD: redhat/Mk/rpmtagname 2017-07-23 16:16:24 -0700 freebsdfrau $
#
############################################################ INFORMATION
#
# Usage: rpmtagname SPECFILE
#
############################################################ GLOBALS

#
# Global exit status
#
SUCCESS=0
FAILURE=1

#
# Utility pathnames
#
: ${AWK:=awk}

############################################################ MAIN

#
# Validate number of arguments
#
[ $# -gt 0 ] || exit $SUCCESS

#
# Get the RPM name from the SPECFILE and return suitable tag name
#
$AWK 'sub(/^[[:space:]]*[Nn][Aa][Mm][Ee]:[[:space:]]*/, ""), \
	gsub(/[^[:alnum:]]!&+,=_-]/, "_")||1' "$1"

################################################################################
# END
################################################################################
