# $FreeBSD: head/usr.sbin/bsdconfig/timezone/Makefile 291347 2015-11-26 01:14:27Z bdrewery $

SUBDIR= include share

FILESDIR=	${LIBEXECDIR}/bsdconfig/090.timezone
FILES=		INDEX USAGE

SCRIPTSDIR=	${FILESDIR}
SCRIPTS=	timezone

.include <bsd.prog.mk>
