# $FreeBSD: head/usr.sbin/bsdconfig/include/Makefile 291347 2015-11-26 01:14:27Z bdrewery $

FILESDIR=	${LIBEXECDIR}/bsdconfig/include
FILES=		bsdconfig.hlp media.hlp messages.subr network_device.hlp \
		options.hlp tcp.hlp usage.hlp

.include <bsd.prog.mk>
