# $FreeBSD: head/usr.sbin/bsdconfig/ttys/Makefile 291347 2015-11-26 01:14:27Z bdrewery $

SUBDIR= include

FILESDIR=	${LIBEXECDIR}/bsdconfig/150.ttys
FILES=		INDEX USAGE

SCRIPTSDIR=	${FILESDIR}
SCRIPTS=	ttys

.include <bsd.prog.mk>
