# $FreeBSD: head/usr.sbin/bsdconfig/networking/share/Makefile 291347 2015-11-26 01:14:27Z bdrewery $

FILESDIR=	${SHAREDIR}/bsdconfig/networking
FILES=		common.subr device.subr hostname.subr ipaddr.subr media.subr \
		netmask.subr resolv.subr routing.subr services.subr

.include <bsd.prog.mk>
