# $FreeBSD: head/usr.sbin/bsdconfig/mouse/Makefile 291347 2015-11-26 01:14:27Z bdrewery $

SUBDIR= include

FILESDIR=	${LIBEXECDIR}/bsdconfig/110.mouse
FILES=		INDEX USAGE

SCRIPTSDIR=	${FILESDIR}
SCRIPTS=	disable enable flags mouse port type

.include <bsd.prog.mk>
