# $FreeBSD: head/usr.sbin/bsdconfig/docsinstall/Makefile 291347 2015-11-26 01:14:27Z bdrewery $

SUBDIR= include

FILESDIR=	${LIBEXECDIR}/bsdconfig/020.docsinstall
FILES=		INDEX USAGE

SCRIPTSDIR=	${FILESDIR}
SCRIPTS=	docsinstall

.include <bsd.prog.mk>
