# $FreeBSD: head/usr.sbin/bsdconfig/timezone/share/Makefile 291347 2015-11-26 01:14:27Z bdrewery $

FILESDIR=	${SHAREDIR}/bsdconfig/timezone
FILES=		continents.subr countries.subr iso3166.subr menus.subr \
		zones.subr

.include <bsd.prog.mk>
