# $FreeBSD: head/usr.sbin/bsdconfig/startup/Makefile 291347 2015-11-26 01:14:27Z bdrewery $

SUBDIR= include share

FILESDIR=	${LIBEXECDIR}/bsdconfig/140.startup
FILES=		INDEX USAGE

SCRIPTSDIR=	${FILESDIR}
SCRIPTS=	misc rcadd rcconf rcdelete rcedit rcvar startup

.include <bsd.prog.mk>
