# $FreeBSD: head/usr.sbin/bsdconfig/usermgmt/share/Makefile 291347 2015-11-26 01:14:27Z bdrewery $

FILESDIR=	${SHAREDIR}/bsdconfig/usermgmt
FILES=		group.subr group_input.subr user.subr user_input.subr

.include <bsd.prog.mk>
