# $FreeBSD: head/usr.sbin/bsdconfig/timezone/include/Makefile 291347 2015-11-26 01:14:27Z bdrewery $

FILESDIR=	${LIBEXECDIR}/bsdconfig/090.timezone/include
FILES=		messages.subr

.include <bsd.prog.mk>
