# $FreeBSD: head/usr.sbin/bsdinstall/Makefile 298107 2016-04-16 07:45:30Z gjb $

SUBDIR= distextract distfetch partedit scripts
SUBDIR_PARALLEL=
SCRIPTS= bsdinstall
MAN= bsdinstall.8
PACKAGE=	bsdinstall

.include <bsd.prog.mk>
