#!/bin/sh
# -*- tab-width: 4 -*- ;; Emacs
# vi: set noexpandtab  :: Vi/ViM
############################################################ IDENT(1)
#
# $Title: Script for importing a directory to git $
# $Copyright: 1999-2017 Devin Teske. All rights reserved. $
# $FrauBSD: pkgcenter/redhat/rhel7-x86_64/Applications/FrauBSD/pkgcenter/stage/usr/pkgcenter/depend/import 2019-07-10 13:30:46 -0700 freebsdfrau $
#
############################################################ INFORMATION
#
# Usage: import PATH ...
#
############################################################ GLOBALS

#
# Global exit status
#
SUCCESS=0
FAILURE=1

#
# Command-line options
#
MESSAGE=	# -m msg

#
# Utility pathnames
#
: ${GIT:=git}

############################################################ MAIN

#
# Process command-line options
#
while getopts m: flag; do
	case "$flag" in
	m) MESSAGE="$OPTARG" ;;
	*) echo "Usage: ${0##*/} [-m msg] PATH ..." >&2
	   exit $FAILURE
	esac
done
shift $(( $OPTIND - 1 ))

set -e
$GIT add "$@"
$GIT commit ${MESSAGE:+-m "$MESSAGE"}

exit $SUCCESS

################################################################################
# END
################################################################################
