# $FreeBSD: head/usr.sbin/bsdconfig/diskmgmt/Makefile 291347 2015-11-26 01:14:27Z bdrewery $

SUBDIR= include

FILESDIR=	${LIBEXECDIR}/bsdconfig/050.diskmgmt
FILES=		INDEX USAGE

SCRIPTSDIR=	${FILESDIR}
SCRIPTS=	diskmgmt

.include <bsd.prog.mk>
