.\" Copyright (c) 2018 Devin Teske <dteske@FreeBSD.org>
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\" $FreeBSD$
.\"
.Dd March 24, 2018
.Dt CMB 1
.Os
.Sh NAME
.Nm cmb
.Nd combinatorics utility
.Sh SYNOPSIS
.Nm
.Op options
.Ar item1
.Ar item2
.Ar ...
.Sh DESCRIPTION
The
.Nm
utility prints combinations,
one per line
.Pq default ,
separated by space
.Pq default .
.Pp
Available options:
.Bl -tag -width ".Fl r Ar range"
.It Fl d Ar text
Delimiter for separating items.
Default is space.
.It Fl i Ar num
Set starting position in combination set.
Default is 1.
.It Fl k Ar range
Number or range
.Pq Qo min..max Qc or Qo min-max Qc
of how many items appear in each combination.
A value of
.Ql 0
.Pq default
calculates all combinations.
.It Fl p Ar text
Prefix each combination with
.Ar text .
.It Fl s Ar text
Suffix each combination with
.Ar text .
.It Fl t
Print total number of combinations and exit.
.El
.Sh HISTORY
The
.Nm
utility first appeared in
.Fx 12.0-CURRENT .
.Sh AUTHORS
.An Devin Teske Aq Mt dteske@FreeBSD.org
