# $FreeBSD: head/usr.sbin/bsdconfig/includes/Makefile 291347 2015-11-26 01:14:27Z bdrewery $

SUBDIR= include

FILESDIR=	${LIBEXECDIR}/bsdconfig/includes
FILES=		INDEX USAGE

SCRIPTSDIR=	${FILESDIR}
SCRIPTS=	includes.sh

.include <bsd.prog.mk>
